version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '4000:4000'
    volumes:
      - ..:/usr/src/app
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - '8080:8080'
    volumes:
      - ..:/usr/src/app
