name: Pull Request Checks
on: [pull_request]
jobs:
  setup:
    name: Setup, test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Set yarn cache dir to env variable
        run: echo "::set-output name=DIR::$(yarn cache dir)"
        id: yarn-cache-dir

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.DIR }}
          key: cache-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: cache-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test and lint
        run: yarn test:all

      - name: Build
        run: yarn build
